### PR TITLE
Update imports to work with Angular 2.0.0-rc.2

### LINKED ISSUE #24: Compilation errors with Angular 2.0.0-rc.2
Trying to compile `angular2-polymer` against the latest RC of Angular 2, we get following compilation errors.

```
src/polymer-element.ts(22,62): error TS2339: Property 'BrowserDomAdapter' does not exist on type '{ DomAdapter: typeof DomAdapter; getDOM: () => DomAdapter; setRootDomAdapter: (adapter: DomAdapte...'.
src/polymer-element.ts(25,10): error TS2339: Property 'appendChild' does not exist on type 'PolymerDomAdapter'.
src/polymer-element.ts(25,34): error TS2339: Property 'createTextNode' does not exist on type 'PolymerDomAdapter'.
src/polymer-element.ts(65,32): error TS2339: Property 'setDOM' does not exist on type '{ DomAdapter: typeof DomAdapter; getDOM: () => DomAdapter; setRootDomAdapter: (adapter: DomAdapte...'.
src/polymer-element.ts(68,32): error TS2339: Property 'setDOM' does not exist on type '{ DomAdapter: typeof DomAdapter; getDOM: () => DomAdapter; setRootDomAdapter: (adapter: DomAdapte...'.
```

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #24

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/25)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/25#-:-KKNscJgMWNIKuv5IR2h:1417088721)_
